### ISSUE TITLE
Error after login

### ISSUE THREAD

**Issue by fhamborg** [UKN-DBVIS/SciBib#7]
```
Warning (512): SplFileInfo::openFile(/var/www/html/tmp/cache/models/myapp_cake_model_default_users): failed to open stream: Permission denied [CORE/src/Cache/Engine/FileEngine.php, line 398]

Warning (512): SplFileInfo::openFile(/var/www/html/tmp/cache/models/myapp_cake_model_default_users) [<a href='http://php.net/splfileinfo.openfile'>splfileinfo.openfile</a>]: failed to open stream: Permission denied [CORE/src/Cache/Engine/FileEngine.php, line 398]

Warning (512): _cake_model_ cache was unable to write 'default_users' to DebugKit\Cache\Engine\DebugEngine cache [CORE/src/Cache/Cache.php, line 248]

Warning (2): Cannot modify header information - headers already sent by (output started at /var/www/html/vendor/cakephp/cakephp/src/Error/Debugger.php:754) [CORE/src/Network/Session.php, line 563]

Warning (2): session_regenerate_id() [<a href='http://php.net/function.session-regenerate-id'>function.session-regenerate-id</a>]: Cannot regenerate session id - headers already sent [CORE/src/Network/Session.php, line 567]
```

**Comment by eren-ck** [comment]
This is a permission error. You have to make the /var/www/html/tmp/ writable by the webserver user.

**Comment by fhamborg** [comment]
According to ls -al it already is writable:
drwxrwxr-x  3 www-data www-data  4096 Feb  5 12:58 tmp

**Comment by eren-ck** [comment]
Could you please modify the permissions with
`chmod 755 -R /var/www/html/tmp`

**Comment by fhamborg** [comment]
OK I did that but it's still giving me the same error / warning after logging in.

Permissions are now:
ubuntu@vm1:/var/www/html$ ls -al /var/www/html/tmp
total 13540
drwxr-xr-x  3 www-data www-data     4096 Feb  6 15:23 .
drwxr-xr-x 12 root     root         4096 Feb  3 12:42 ..
drwxr-xr-x  4 www-data www-data     4096 Jan 29 15:56 cache
-rwxr-xr-x  1 www-data www-data 13845504 Feb  6 15:23 debug_kit.sqlite

**Comment by eren-ck** [comment]
Please delete the cakephp cache with 
`rm -rf /var/www/html/tmp/cache/*` 
and clear your browser history.

**Comment by fhamborg** [comment]
great, that solved the issue
